apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gatling-load-tests-build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/royteeuwen/gatling-load-tests.git'
      ref: main
    #contextDir: dockerfile
  strategy:
    type: Docker
    #With this you can set a path to the docker file
    #dockerStrategy:
    # dockerfilePath: dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'gatling-load-tests:latest'
